# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - chat-app-backend

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: npm install
        run: npm install

      - name: Zip artifact for deployment
        run: zip -r release.zip . -x "*.git/*" "node_modules/*" 

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: chat-app-backend
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write 

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: chat-app-backend

      - name: Check if release.zip exists
        run: |
          if [ -f "release.zip" ]; then
            echo "release.zip exists."
          else
            echo "release.zip does not exist."
            exit 1
          fi

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: List files after unzipping
        run: ls -alh 

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID }}

      - name: Verify Azure login
        run: az account show

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'chat-app-backend'
          slot-name: 'Production'
          package: . 
