name: Build and deploy Node.js app to Azure Web App - mongodbatlasazurenodejs

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from GitHub
      - uses: actions/checkout@v2
      
      # Set up Node.js environment
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      # Install backend dependencies
      - name: Install npm packages
        run: |
          npm install

      # Upload artifact for deployment job
      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v2
        with:
          name: backend-app
          path: .
          
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      # Download artifact from the build job
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: backend-app

      # Deploy to Azure Web App
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'mongodbatlasazurenodejs'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          package: .
